home/urls.py
from django.conf.urls import url
from home.views import HomeView

from . import views

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^publish_call$', views.pub, name='pub'),
    url(r'^delete_call/(?P<call_id>\d+)$', views.delete_call, name='delete_call'),
    url(r'^delete_proposal/(?P<proposal_id>\d+)$', views.delete_proposal, name='delete_proposal'),
    url(r'^call_view$', views.get_call_view, name='call_view'),
    url(r'^my_calls$', views.get_my_calls, name='my_calls'),
    url(r'^download_file$', views.download_file, name='download_file'),
    url(r'^centers$', views.view_center, name='view_center'),
    url(r'^centers/create_center$', views.create_center, name='create_center'),
    url(r'^ajax/autocomplete/$', views.autocomplete, name='ajax_autocomplete'),
    url(r'^nav_search$', views.nav_search, name='nav_search'),
    url(r'^add_to_center$', views.add_to_center, name='add_to_center'),
    url(r'^update_proposal$', views.update_proposal, name='update_proposal'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from project import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),

]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/forms.py
from django import forms
import datetime

class PublishForm(forms.Form):
    First_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control is-valid",'value': "{{ user.first_name }}"}))
    Surname = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control is-valid",'value': "{{ user.last_name }}"}))
    # Deadline_for_calls = forms.DateField(initial=datetime.date.today,widget=forms.SelectDateWidget())

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic import TemplateView
from django.shortcuts import render, HttpResponse, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.static import serve
from django.http import JsonResponse
from django.db.models import Q
from .forms import PublishForm
from accounts.models import Call, Center, Proposal, Reviewer ,Funder, Researcher
from accounts.forms import CenterForm, ProposalForm
import MySQLdb as _db
import os
import datetime
from django.contrib import messages
import zipfile
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import get_template
from django.contrib.auth.models import User
from accounts.models import Researcher


host_name = "mysql.netsoc.co"
user_name = "nadehh"
password = "HjOEsz2C483h"
db_name = "nadehh_db_final"
db_info_string="< %s > @ < %s >"%(db_name,host_name)
result = "fail"

class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get(self, request):
        tableData = Call.objects.all()
        context = {'tableData':tableData}
        return render(request, self.template_name, context)

def view_center(request):
    center_obj = Center.objects.filter(members=request.user.id)
    context = {'center_obj':center_obj}
    return render(request, 'home/view_center.html', context)

def create_center(request):
    if request.method == 'POST':
        form = CenterForm(request.POST)
        if form.is_valid():
            form.save(admin=request.user)
            messages.success(request, "Your center has been created!")
            return redirect(reverse('home:view_center'))
    else:
        form = CenterForm()
    return render(request, 'home/create_center.html', {'form': form})

def download_file(request):
    if request.method == "GET":
        filepath = request.GET.get("filename")
        zipName = "zipped.zip"
        zipFileName = "%s/%s" % (filepath,zipName)
        zip = zipfile.ZipFile(zipFileName,"w")
        for file in os.listdir(filepath):
             if file!=zipName:
                 fullPath = "%s/%s"%(filepath,file)
                 zip.write(fullPath,os.path.basename(file),zipfile.ZIP_DEFLATED)
        zip.close()
        return serve(request, os.path.basename(zipFileName), os.path.dirname(zipFileName))


def get_call_view(request):
    files = []
    call_obj = None
    call_id = None
    if request.method == 'GET':
        call_id = request.GET.get('call_id', '')
        call_obj = Call.objects.get(pk=call_id)
        call_id = request.GET.get('call_id', '')
        call_obj = Call.objects.filter(pk=call_id).values()
        context = {'call_obj':call_obj}

        funder_id = call_obj[0]['funder_id']
        user = str(request.user)
        userFileDir = "calls/%s-%s/calls"%(funder_id,call_id)
        files.append(userFileDir)
        return render(request, 'home/call_view.html', {'call_obj':call_obj,"link_obj":files,"call_id":call_id})

    else:
        call_id = request.POST.get('call_id', '').decode('utf-8')
        call_obj = Call.objects.filter(pk=call_id).values()
        funder_id = call_obj[0]['funder_id']
        filenames = []

        user = str(request.user)
        userFileDir = "calls/%s-%s/calls"%(funder_id,call_id)
        if not os.path.isdir(userFileDir):
            os.makedirs(userFileDir)


        for key in request.FILES:
            file = request.FILES[key]
            filenames.append(str(file))
            with open("%s/%s"%(userFileDir,file.name),"wb+") as saveFile:
                for line in file:
                    saveFile.write(line)

        filename = ','.join(filenames)
        id = request.user.id
        call_id = int(call_id)

        connection = _db.connect(host=host_name,
                         user=user_name,
                         passwd=password,
                         db=db_name)

        result = "success"

        try:
            cursor = connection.cursor()
            cursor.execute("""
                select user_id from reviewers order by rand() limit 1
            """)
            reviewer_id = cursor.fetchall()[0][0]
        except db.Error:
            reviewer_id = None

        db = Proposal(proposal_document=filename,call_id=call_id,user_id=id,reviewer_id=reviewer_id)
        db.save()
        return render(request, 'home/my_calls.html')

def delete_proposal(request, proposal_id):
    Proposal.objects.get(pk=int(proposal_id)).delete()
    messages.success(request, "Your proposal has been deleted!")
    return redirect(reverse("home:my_calls"))

def delete_call(request, call_id):
    Call.objects.get(pk=int(call_id)).delete()
    messages.success(request, "Your call has been deleted!")
    return redirect(reverse("home:my_calls"))

def get_my_calls(request):
    user = request.user

    try:
        funder = user.funder
        my_call_table_data = Call.objects.filter(funder_id=user.id).values()
        context = {'my_call_table_data':my_call_table_data,'type':'funder'}
        return render(request, 'home/my_calls.html', context)
    except Funder.DoesNotExist:
        print("Not funder")

    try:
        researcher = user.researcher
        proposals = Proposal.objects.select_related('call').filter(user=user)
        my_call_table_data = [prop.call for prop in proposals]
        context = {'my_call_table_data':my_call_table_data, 'type':'researcher', 'proposals':proposals}
        return render(request, 'home/my_calls.html', context)
    except Researcher.DoesNotExist:
        print("Not researcher")

    try:
        reviewer = user.reviewer
        proposals = Proposal.objects.select_related('call').filter(reviewer_id=user.id)
        my_call_table_data = [prop.call for prop in proposals]
        context = {'my_call_table_data':my_call_table_data, 'type':'reviewer', 'proposals':proposals}
        return render(request, 'home/my_calls.html', context)
    except Reviewer.DoesNotExist:
        print("Not reviewer")


def pub (request):
    categories = []
    edit_info = []
    connection = None
    edit_toggle = False
    funds = ["€10,000 - €25,000","€25,000 - €50,000","€50,000 - €100,000","€100,000 - €250,000","€250,000 - €500,000","€500,000 - €1,000,000","€1,000,000 - €2,000,000"]
    editing_mode = False
    now = datetime.datetime.now()
    date_string = "%s-%s-%s"%(now.year,now.month,now.day)
    call_id = None

    if request.method == "POST":
       now = datetime.datetime.now()
       date_string = "%s-%s-%s"%(now.year,now.month,now.day)
       fname = request.POST.get("fname")
       sname = request.POST.get("sname")
       eligibility = request.POST.get("tag")
       title = request.POST.get("title")
       description = request.POST.get("description")
       deadline = request.POST.get("date")
       grant = request.POST.get("grant")
       funder_id = request.user.id

       value = request.POST.get("editing_mode")

       email_users(request, title, grant, eligibility)
        
       if value == "True":
           print("in editing mode man")
           editing_mode = True

       call_id = request.POST.get("_call_id")
       filenames = []
        
       for key in request.FILES:
           file = str(request.FILES[key])
           print(file)
           filenames.append(file)

       filename = ', '.join(filenames)

       db_query = """

           INSERT INTO calls (target, created, funder_id, title, description, deadline,funds, file_location )
           VALUES ("%s","%s","%s","%s","%s","%s","%s","%s");

       """ %(eligibility,date_string,funder_id,title,description,deadline,grant,filename)

       if editing_mode:
          db_query = """

              UPDATE calls
              SET target="%s",
                  created="%s",
                  funder_id=%d,
                  title="%s",
                  description="%s",
                  deadline="%s",
                  funds="%s"
              WHERE id = %d;

          """ %(eligibility,date_string,int(funder_id),title,description,deadline,grant,int(call_id))

       try:                        
           connection = _db.connect(host=host_name,
                            user=user_name,
                            passwd=password,
                            db=db_name)

           result = "success"
           cursor = connection.cursor()

           cursor.execute(db_query)

           if not editing_mode:
               id = cursor.lastrowid

               user = str(request.user.id)
               userFileDir = "calls/%s-%s/calls"%(user,id)

               if not os.path.isdir(userFileDir):
                   os.makedirs(userFileDir)

               for key in request.FILES:
                   file = request.FILES[key]
                   with open("%s/%s"%(userFileDir,file.name),"wb+") as saveFile:
                       for line in file:
                           saveFile.write(line)

           connection.commit()

       except _db.Error as e:
           print("Error connecting to the database.. check credentials!")
           print(e)

       finally:
           connection.close()
            
       return redirect(reverse("home:my_calls"))

    if request.method == 'GET':
        try:
            connection = _db.connect(host=host_name,
                             user=user_name,
                             passwd=password,
                             db=db_name)

            result = "success"
            cursor = connection.cursor()
            cursor.execute("""

                SELECT category FROM categories;

            """)

            for row in cursor.fetchall():
                categories.append(row[0].strip("\n"))

            call_id = request.GET.get("call_id")

            if call_id is not None:
                edit_toggle = True

                cursor.execute("""

home/templates/home/call_view.html
{% extends 'base.html' %}

<head>
    {% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'publishCalls/index.css' %}">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'publishCalls/index.css' %}">
    <link rel="stylesheet" href="{% static 'publishCalls/dist/dropzone.css' %}">
    <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script defer src="{% static 'publishCalls/dist/dropzone.js' %}"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script defer src="{% static 'publishCalls/newdragNdropCalls.js' %}" charset="utf-8"></script>
    {% endblock %}
</head>
{% block body %}
<br><br>
<div class="container">
  <div class="row">
    <div class="col-sm-6 offset-sm-3 text-center" style="background-color:#F5F5F5;">
      {% for item in call_obj %}
      <h1 style="font-size=3vw;"> {{ item.title }}</h1><br>

      <div class="col text-left" style="font-size:1.5vw">
      <!--  <p style="font-size:1.5vw">Title: {{ item.title }}</p> -->
        <p>Funds: {{ item.funds }}</p>
        <p>Deadline: {{ item.deadline }}</p>
        <p>Target: {{ item.target }}</p>
        <p>Created: {{ item.created }}</p>
        <p>Funder ID: {{ item.funder_id }}</p>
        <p style="margin-bottom:0; padding-bottom:0">Description: {{ item.description }}</p>
      </div>
  {% endfor %}

{% if user.researcher %}
      <div class="container">
          <!-- <form method="post" enctype="multipart/form-data"> -->
            {% csrf_token %}
              <!-- {{ form.as_p }} -->
                <input id="call_id" type="hidden" value={{ call_id }}>
            <section id="dz">
                <div id="dropbox" class="dropzone"</div><br>
            </section><br>
            <button id="btn" type="button" class="btn btn-success btn-large text-center">Apply</button>

            <div id="prog" class="progress">
                <div id="progress" class="progress-bar progress-bar-striped bg-info active bg-dark" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:0%"> 0% </div>
            </div>
            <!-- <button class="btn btn-success" type="submit">Apply</button> -->
        <!-- </form> -->
        {% endif %}
        {% for i in link_obj %}
        <a href="http://127.0.0.1:8000/home/download_file?filename={{ i }}" download> Click here to download documents </a>
        {% endfor %}
    </div>
    </div>
  </div>

{% endblock %}

home/templates/home/create_center.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<head>
    {% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'publishCalls/index.css' %}">
    {% endblock %}
</head>
{% block body %}
<br>
<div class="container">
    <h1>Create a Center</h1>
</div>
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Create Center</button>
    </form>
</div>

{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

<head>
    {% block head %}

    <meta charset="UTF-8">
    {% endblock %}
</head>

{% block body %}
<div class="container" id="first_container">
    <div class="container">
        <div class="col-xs-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <center>{{ message }}</center>
            </div>
            {% endfor %}
            {% endif %}
        </div>
      <div class="row">
        <div class="col-sm-10">
          <h1>Published Calls</h1>
        </div>
        <div class="col-sm-2">
            {% if user.funder %}
            <form action="{% url 'home:pub' %}">
                <button class="btn btn-success" type='submit'>Create Call</button>
            </form>
            {% endif %}
        </div>
      </div>

    <section id="summary">
        <table id="example" class="table table-borderless" style="width:100%">
          <thead style="background-color:teal; color:white;">
          <tr>
              <th> Posted </th>
              <th> Title of call </th>
              <th> Grant range </th>
              <th> Deadline </th>
              <th> Target audience </th>
          </tr>
          </thead>
          <tbody>
          {% for item in tableData %}
          <tr>
              <td id="s_created">{{ item.created }}</td>
              <td id="s_title"><a href="{% url 'home:call_view' %}?call_id={{ item.id }}"> {{ item.title }} </a></td>
              <td id="s_amount">{{ item.funds }}</td>
              <td id="s_deadline">{{ item.deadline }}</td>
              <td id="s_target">{{ item.target }}</td>
          </tr>
          {% endfor %}
         </tbody>
        </table>
    </section>
</div>
{% endblock %}

home/templates/home/my_calls.html
{% extends 'base.html' %}

<head>
    {% block head %}
    {% endblock %}
</head>

{% block body %}
<div class="container" id="first_container">
    <div class="container">
        <div class="col-xs-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <center>{{ message }}</center>
            </div>
            {% endfor %}
            {% endif %}
        </div>
      <div class="row">
        <div class="col-sm-10">
            {% if type == 'researcher' or type == 'reviewer' %}
            <h1>My Proposals</h1>
            {% else %}
            <h1>My Calls</h1>
            {% endif %}
        </div>
        <div class="col-sm-2">
            {% if type == 'funder' %}
            <form action="{% url 'home:pub' %}">
                <button class="btn btn-success" type='submit'>Create Call</button>
            </form>
            {% endif %}
        </div>
      </div>
    {% if type == 'funder' %}
    <section id="summary">
      <table id="example" class="table table-borderless" style="width:100%">
        <thead style="background-color:teal; color:white;">
          <tr>
              <th> Posted </th>
              <th> Title of call </th>
              <th> Grant range </th>
              <th> Deadline </th>
              <th> Target audience </th>
              <th></th>
              <th></th>
          </tr>
          </thead>
          <tbody>
          {% for item in my_call_table_data %}
          <tr>
              <td id="s_created">{{ item.created }}</td>
              <td id="s_title"><a href="{% url 'home:call_view' %}?call_id={{ item.id }}"> {{ item.title }} </a></td>
              <td id="s_amount">{{ item.funds }}</td>
              <td id="s_deadline">{{ item.deadline }}</td>
              <td id="s_target">{{ item.target }}</td>
              <td><a href="{% url 'home:pub' %}?call_id={{ item.id }}" class="btn btn-info">Edit</a></td>
              <td><a href="{% url 'home:delete_call' item.id %}" class="btn btn-danger">Delete</a></td>
          </tr>
          {% endfor %}
         </tbody>

        </table>
    </section>
    {% elif type == 'researcher' %}
    <section id="summary">
      <table id="example" class="table table-borderless" style="width:100%">
        <thead style="background-color:teal; color:white;">
          <tr>
              <th> Posted </th>
              <th> Title of call </th>
              <th> Grant range </th>
              <th> Deadline </th>
              <th> Target audience </th>
              <th> Status </th><th></th>
          </tr>
          </thead>
          <tbody>
          {% for item in proposals %}
              <tr>
                  <td id="s_created">{{ item.call.created }}</td>
                  <td id="s_title"><a href="{% url 'home:call_view' %}?call_id={{ item.call.id }}"> {{ item.call.title }} </a></td>
                  <td id="s_amount">{{ item.call.funds }}</td>
                  <td id="s_deadline">{{ item.call.deadline }}</td>
                  <td id="s_target">{{ item.call.target }}</td>
                  <td>{{ item.status }}</td>
                  <td><a href="{% url 'home:delete_proposal' item.id %}" class="btn btn-danger">Delete</a></td>
              </tr>
          {% endfor %}

         </tbody>

        </table>
    </section>
    {% else %}
    <section id="summary">
      <table id="example" class="table table-borderless" style="width:100%">
        <thead style="background-color:teal; color:white;">
          <tr>
              <th> Posted </th>
              <th> Title of call </th>
              <th> Deadline </th>
              <th> Target audience </th>
              <th> Status </th>
              <th> Update Status </th>
          </tr>
          </thead>
          <tbody>
          {% for item in proposals %}
              <tr>
                  <td id="s_created">{{ item.call.created }}</td>
                  <td id="s_title"><a href="{% url 'home:call_view' %}?call_id={{ item.call.id }}"> {{ item.call.title }} </a></td>
                  <td id="s_deadline">{{ item.call.deadline }}</td>
                  <td id="s_target">{{ item.call.target }}</td>
                  <td>{{ item.status }}</td>
                  <td>
                      <form class="update_status" action="{% url 'home:update_proposal' %}" method="get">
                          <input type="hidden" name="id" value="{{ item.id }}">
                          <select name="status">
                            <option value="o" selected></option>
                            <option value="p">Pending</option>
                            <option value="r">Reviewed</option>
                            <option value="a">Accepted</option>
                            <option value="d">Denied</option>
                          </select>
                          <button class="btn btn-success" type='submit'>Update</button>
                      </form>
                  </td>
              </tr>
          {% endfor %}
         </tbody>

        </table>
    </section>
    {% endif %}
</div>
{% endblock %}

home/templates/home/nav_search.html
{% extends 'base.html' %}

<head>
    {% block head %}
    {% endblock %}
</head>

{% block body %}
<br>
<section id='tables'>
  {% if centerQuerySet %}
  <div class="container">
    <h2>Centers</h2>
    <table id="center-table" class="table table-borderless" style="width:100%">
      <thead style="background-color:teal; color:white;">
        <tr>
          <th>Name</th>
          <th> Date Created </th>
          <th> More Info </th>
        </tr>
      </thead>
      <tbody>
        {% for item in centerQuerySet %}
        <tr>
          <td id="center-name">{{ item.name }}</td>
          <td id='center-date'>{{ item.created }}</td>
          <td id='center-info'>{{ item.info }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  {% if researcherQuerySet %}
  <div class="container">
    <h2>Researchers</h2>
    <table id="researcher-table" class="table table-borderless" style="width:100%">
      <thead style="background-color:teal; color:white;">
        <tr>
          <th> First Name </th>
          <th> Last Name </th>
          <th> Job Title </th>
        </tr>
      </thead>
      <tbody>
        {% for item in researcherQuerySet %}
        <tr>
          <td id='researcher-fname'><a href="../../account/view-researcher/{{ item.user.id }}">{{ item.user.first_name }}</a></td>
          <td id='researcher-lname'><a href="../../account/view-researcher/{{ item.user.id }}">{{ item.user.last_name}}</a></td>
          <td id='researcher-title'>{{ item.job_title }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <p> No search results </p>
{% endif %}
{% endif %}
</section>
{% endblock %}

home/templates/home/view_center.html
{% extends 'base.html' %}

<head>
    {% block head %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'publishCalls/index.css' %}">
    {% endblock %}
</head>
{% block body %}
<br>

<div class="container">
    <div class="col-xs-12">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            <center>{{ message }}</center>
        </div>
        {% endfor %}
        {% endif %}
    </div>
  <h1>Centers</h1>
  {% if result %}
    {% if result == 'success' %}
      <p>User Successfully Added to Center!</p>
    {% else %}
      <p>User Email Does Not Exist!</p>
    {% endif %}
  {% endif %}
  {% if center_obj %}
  <table id="example" class="table table-borderless" style="width:100%">
    <thead style="background-color:teal; color:white;">
    <tr>
        <th> Name </th>
        <th> Description </th>
        <th> Created </th>
        <th> Admin </th>
        <th> Add User to Center </th>
    </tr>
    </thead>
    <tbody>
      {% for item in center_obj %}
    <tr>
        <td>{{ item.name }} </td>
        <td>{{ item.info }} </td>
        <td>{{ item.created }} </td>
        <td>{{ item.admin_id }} </td>
        {% if item.admin_id == user.id %}
        <td>
          <form class="add_user form-inline" action="{% url 'home:add_to_center' %}" method="get">
            <input type="text" class="form-control" style="width:80%" name="user_email" placeholder="User Email">
            <button class="btn btn-success" style="margin-left:5px" type="submit">Add</button>
            <input type="hidden" name="center" value="{{ item.name }}">
          </form>
        </td>

        {% endif %}
    </tr>
      {% endfor %}
   </tbody>
  </table>
    {% else %}
    <i><p>Not part of a center, create a center below</p></i>
    {% endif %}

    <form action="{% url 'home:create_center' %}">
        <button class="btn btn-success" type='submit'>Create Center</button>
    </form>
  </div>
{% endblock %}