accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import   (
    login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset,
    {'template_name': 'accounts/reset_password.html',
    'post_reset_redirect': 'accounts:password_reset_done',
    'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,
    {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html',
    'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

    url(r'^view-researcher/(?P<researcher_id>\d+)/$', views.view_researcher, name='view researcher'),
    url(r'^view-researcher/(?P<researcher_id>\d+)/education/new', views.add_education),
    url(r'^view-researcher/(?P<researcher_id>\d+)/education/(?P<index>\d+)', views.edit_education),
    url(r'^view-researcher/(?P<researcher_id>\d+)/employment/new', views.add_employment),
    url(r'^view-researcher/(?P<researcher_id>\d+)/employment/(?P<index>\d+)', views.edit_employment),
    url(r'^view-researcher/(?P<researcher_id>\d+)/society/new', views.add_society),
    url(r'^view-researcher/(?P<researcher_id>\d+)/society/(?P<index>\d+)', views.edit_society),
    url(r'^view-researcher/(?P<researcher_id>\d+)/award/new', views.add_award),
    url(r'^view-researcher/(?P<researcher_id>\d+)/award/(?P<index>\d+)', views.edit_award),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding/new', views.add_funding),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding/(?P<index>\d+)', views.edit_funding),
    url(r'^view-researcher/(?P<researcher_id>\d+)/team_member/new', views.add_team_member),
    url(r'^view-researcher/(?P<researcher_id>\d+)/team_member/(?P<index>\d+)', views.edit_team_member),
    url(r'^view-researcher/(?P<researcher_id>\d+)/impact/new', views.add_impact),
    url(r'^view-researcher/(?P<researcher_id>\d+)/impact/(?P<index>\d+)', views.edit_impact),
    url(r'^view-researcher/(?P<researcher_id>\d+)/innovation/new', views.add_innovation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/innovation/(?P<index>\d+)', views.edit_innovation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/publication/new', views.add_publication),
    url(r'^view-researcher/(?P<researcher_id>\d+)/publication/(?P<index>\d+)', views.edit_publication),
    url(r'^view-researcher/(?P<researcher_id>\d+)/presentation/new', views.add_presentation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/presentation/(?P<index>\d+)', views.edit_presentation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/acedemic-collab/new', views.add_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/acedemic-collab/(?P<index>\d+)', views.edit_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/non_acedemic_collab/new', views.add_non_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/non_acedemic_collab/(?P<index>\d+)', views.edit_non_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/conference/new', views.add_conference),
    url(r'^view-researcher/(?P<researcher_id>\d+)/conference/(?P<index>\d+)', views.edit_conference),
    url(r'^view-researcher/(?P<researcher_id>\d+)/comms_overview/new', views.add_comms_overview),
    url(r'^view-researcher/(?P<researcher_id>\d+)/comms_overview/(?P<index>\d+)', views.edit_comms_overview),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding_ratio/new', views.add_funding_ratio),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding_ratio/(?P<index>\d+)', views.edit_funding_ratio),
    url(r'^view-researcher/(?P<researcher_id>\d+)/project/new', views.add_project),
    url(r'^view-researcher/(?P<researcher_id>\d+)/project/(?P<index>\d+)', views.edit_project)
]

home/urls.py
from django.conf.urls import url
from home.views import HomeView

from . import views

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^publish_call$', views.pub, name='pub'),
    url(r'^delete_call/(?P<call_id>\d+)$', views.delete_call, name='delete_call'),
    url(r'^delete_proposal/(?P<proposal_id>\d+)$', views.delete_proposal, name='delete_proposal'),
    url(r'^call_view$', views.get_call_view, name='call_view'),
    url(r'^my_calls$', views.get_my_calls, name='my_calls'),
    url(r'^download_file$', views.download_file, name='download_file'),
    url(r'^centers$', views.view_center, name='view_center'),
    url(r'^centers/create_center$', views.create_center, name='create_center'),
    url(r'^ajax/autocomplete/$', views.autocomplete, name='ajax_autocomplete'),
    url(r'^nav_search$', views.nav_search, name='nav_search'),
    url(r'^add_to_center$', views.add_to_center, name='add_to_center'),
    url(r'^update_proposal$', views.update_proposal, name='update_proposal'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from project import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),

]

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import *


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

class CenterForm(forms.ModelForm):
    class Meta:
        model = Center
        fields = ('name', 'info')

    def save(self, admin, commit=True):
        center = super(CenterForm, self).save(commit=False)
        center.admin = admin
        if commit:
            center.save()
            center.members.add(admin)
        return center

class CallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = '__all__'
        exclude = ('created', 'funder')

class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ('proposal_document',)

    def save(self, user, call, reviewer=None, commit=True):
        proposal = super(ProposalForm, self).save(commit=False)
        proposal.user = user
        proposal.call = call
        proposal.reviewer = reviewer
        proposal.status = "p"
        if commit:
            proposal.save()
        return proposal

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        exclude = ('researcher', 'center')

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from accounts.forms import EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseForbidden
from accounts.models import *

# Create your views here.
def register(request):
    errors = []
    if request.method == 'POST':
        type = request.POST['user_type']
        user = User()
        email = request.POST['email']
        if len(User.objects.filter(email=email)) != 0:
            errors += ["Email address already in use"]
        user.email = email
        user.first_name = request.POST.get('first_name', None)
        user.last_name = request.POST.get('last_name', None)
        password = request.POST['password']
        user.set_password(password)
        user.username = email
        if type == 'funder':
            other = Funder()
            other.organisation = request.POST.get('organisation', None)
        elif type == 'reviewer':
            other = Reviewer()
            other.field = request.POST.get('field', None)
        else:
            other = Researcher()
            other.job_title = request.POST.get('job_title', None)
            other.prefix = request.POST.get('prefix', None)
            other.suffix = request.POST.get('suffix', None)
            other.phone = request.POST.get('phone', None)
            other.orcid = request.POST.get('orcid', None)
        if not errors:
            user.save()
            other.user = user
            other.save()
            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
            return redirect(reverse('home:home'))

    return render(request, 'accounts/reg_form.html', {'errors' : errors})

def view_profile(request):
    try:
        researcher = request.user.researcher
        return redirect("/account/view-researcher/%s" % request.user.id)
    except Researcher.DoesNotExist:
        storage = messages.get_messages(request)
        args = {'user': request.user, 'message': storage}
        return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method=='POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was updated!')
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method=="POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your new password has been saved!')
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))

    else:
        form = PasswordChangeForm(user=request.user)

    args = {'form': form}
    return render(request, 'accounts/change_password.html', args)


# Researcher profile views:


# view the researcher with the id researcher_id and view it with
# editing if the logged in user IS the researcher
def view_researcher(request, researcher_id):
    researcher_id = int(researcher_id)
    editing = request.user.id == researcher_id
    if editing:
        researcher = request.user.researcher
    else:
        researcher = Researcher.objects.get(user=researcher_id)
    return render(request, 'accounts/view_researcher.html', {'researcher': researcher, 'profile':researcher.profile, 'editing': editing})




def add_education(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Education',
            'is_private' : True,
            'inputs' : Education.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_education().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#education_%i' % (researcher_id, obj.index))

def edit_education(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.educations[index]
        attributes = {
            'title' : 'Edit Education',
            'is_private' : obj.is_private,
            'inputs' : Education.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.educations[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#educations_%i" % (researcher_id, index))

def add_employment(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Employment',
            'is_private' : True,
            'inputs' : Employment.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_employment().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#employment_%i' % (researcher_id, obj.index))

def edit_employment(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.employments[index]
        attributes = {
            'title' : 'Edit Employment',
            'is_private' : obj.is_private,
            'inputs' : Employment.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.employments[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#employment_%i" % (researcher_id, index))

def add_society(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Society',
            'is_private' : True,
            'inputs' : Society.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_society().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#society_%i' % (researcher_id, obj.index))

def edit_society(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.societies[index]
        attributes = {
            'title' : 'Edit Society',
            'is_private' : obj.is_private,
            'inputs' : Society.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.societies[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#society_%i" % (researcher_id, index))

def add_award(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Award',
            'is_private' : True,
            'inputs' : Award.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_award().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#award_%i' % (researcher_id, obj.index))

def edit_award(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.awards[index]
        attributes = {
            'title' : 'Edit Award',
            'is_private' : obj.is_private,
            'inputs' : Award.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.awards[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#award_%i" % (researcher_id, index))

def add_funding(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<title>Change Password</title>

{% block body %}
<br>
<div class="container" style="margin-left:2px">
  <h1> Change password</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Save</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% block head %}
    <style media="screen">
        strong {
            color: red;
        }
        label {
            text-align: left;
        }
    </style>
    <title>{{ title }}</title>
{% endblock %}
{% block body %}
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4 offset offset-sm-4 text-center" style="background-color:#F5F5F5; border:2px solid teal; padding:10px;">

    <h2>{{ title }}</h2>
    <div id="errors">
        {% for error in errors %}
        <p><strong>{{ error }}</strong></p>
        {% endfor %}
    </div>
    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="is_private">Is private</label></td>
                <td><input class="text-center"type="checkbox" name="is_private" {% if is_private %}checked{% endif %}></td>
            </tr>
            {% for input in inputs %}
                <tr>
                    <td>

                        <label for="{{ input.name }}">{{ input.label }}</label>
                    </td>
                    <td>
                        <input class="form-control" type="text" name="{{ input.name }}" value="{{ input.value }}">
                    </td>
                </tr>
            {% endfor %}
        </table>
        <button class="btn btn-success" type="submit">Save</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-4 offset-sm-4 text-center" style="background-color:#F5F5F5; border:2px solid teal; height:450px;">
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group text-left">
          <label for="id_username">Username</label>
          <input type="text" class="form-control" name="username" maxlength="254" required /autofocus id="id_username"/>
        </div>
        <div class="form-group text-left">
          <label for="id_password" >Password</label>
          <input type="password" class="form-control" name="password" required id="id_password"/>
        </div><br>
        <button class="btn btn-success" type="submit">Login</button>
        <br><br>
        <p><u><a href="{% url 'accounts:reset_password' %}">Forgotten password?</a></u></p>

        <p><u><a href="{% url 'accounts:register' %}">Not yet registered? Create an account</a></u></p>
    </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm-4 offset-sm-4 text-center" style="padding-top:100px">
    <h1 style="font-size:4vw;">Logged Out</h1>
    <br>
    <p><u><a href="{% url 'accounts:login' %}">Want to log back in?</a></u></p>
</div>

{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Reset Password</h1>
    <p>
        Enter your email here to reset your password
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-default" type="submit">Send</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

<title>Profile</title>

{% block body %}
<br>
<div class="container" style="margin-left:2px">
    <div class="container">
        <div class="col-xs-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <center>{{ message }}</center>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <h1>Account details</h1>
        <h5>First name:{{ user.first_name }}</h5>
        <h5>Last name: {{ user.last_name }}</h5>
        <h5>Email: {{ user.email }}</h5>
    </div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'accounts/register.js' %}"></script>
    <style media="screen">
        strong {
            color: red;
        }
    </style>
    <title>Register</title>
    {% endblock %}
{% block body %}
<br>
<div class="row">
  <div class="col-sm-4 offset-sm-4 text-center" style="background-color:#F5F5F5; border:2px solid teal;">
    <h1>Register</h1>
    <div class="container">
        <div id="errors">
            {% for error in errors %}
            <p><strong>{{ error }}</strong></p>
            {% endfor %}
        </div>
        <form id="reg" method="post">
            {% csrf_token %}
            <div class="form-group text-left">
              <label for="user_type" class="col-form-label ">Register as </label>
              <select id="user_type" class="user_type form-control" name="user_type" required>
                <option selected disabled hidden style='display: none' value=''></option>
                <option value="researcher">Researcher</option>
                <option value="funder">Funding Authority</option>
                <option value="reviewer">Reviewer</option>
              </select>
            </div>
            <div class="form-group text-left">
              <label class="user_form" hidden for="email">Email</label>
              <input class="user_form form-control" hidden id="email" type="email" name="email" autocomplete="email" placeholder="example@example.com" required>
            </div>


            <div class="form-group text-left">
              <label class="user_form" hidden for="first_name">First Name</label>
              <input class="user_form form-control" hidden type="text" id="first_name" autocomplete="first name" name="first_name" required>
            </div>

            <div class="form-group text-left">
              <label class="user_form" hidden for="last_name">Last Name</label>
              <input class="user_form form-control" hidden type="text" id="last_name" autocomplete="family-name" name="last_name" required>
            </div>

            <div class="form-group text-left">
              <label class="user_form" hidden for="password1">Password</label>
              <input class="user_form form-control" hidden id="password1" type="password" name="password" required/>
            </div>

            <div class="form-group text-left">
              <label class="user_form" hidden for="password2">Repeat Password</label>
              <input class="user_form form-control" hidden id="password2" type="password" required/><p><strong id="no_match" hidden>Passwords do not match</strong></p>
            </div>
            <div id="researcher_form" hidden>
              <div class="form-group text-left">
                <label for="job_title">Job Title</label>
                <input id="job_title" type="text" name="job_title" class="res_req form-control">
              </div>
              <div class="form-group text-left">
                <label for="prefix">Prefix</label>
                <select class="prefix res_req form-control" id="prefix" name="prefix">
                    <option selected disabled hidden style='display: none' value=''></option>
                    <option value="mr">Mr</option>
                    <option value="ms">Ms</option>
                    <option value="rs">Mrs</option>
                    <option value="mx">Mx</option>
                    <option value="dr">Dr</option>
                    <option value="pr">Prof</option>
                </select>
              </div>
              <div class="form-group text-left">
                <label for="suffix" >Suffix</label>
                <input type="text" id="suffix" autocomplete="honorific-suffix" name="suffix" maxlength="10" class="form-control">
              </div>
              <div class="form-group text-left">
                <label for="phone">Phone number</label>
                <input type="tel" id="phone" autocomplete="tel" name="phone" class="form-control">
              </div>
              <div class="form-group text-left">
                <label for="orcid">ORCID number</label>
                <input type="text" id="orcid" name="orcid" placeholder="XXXX-XXXX-XXXX-XXXX" class="form-control">
              </div>
            </div>
              <!--<br><label for="profile_picture">Profile Picture</label>
              <input type="file" id="profile_picture" name="profile_picture">-->
            <div id="reviewer_form" hidden>
              <div class="form-group text-left">
                <label for="field">Field of research</label>
                <select class="field form-control" name="field" id="field">
                    <option selected disabled hidden style='display: none' value=''></option>
                    <option value="A">Priority Area A: Future Networks & Communications</option>
                    <option value="B">Priority Area B: Data Analytics, Management, Security & Privacy</option>
                    <option value="C">Priority Area C: Digital Platforms, Content & Applications</option>
                    <option value="D">Priority Area D: Connected Health & Indepentant Living</option>
                    <option value="E">Priority Area E: Medical Devices</option>
                    <option value="F">Priority Area F: Diagnostics</option>
                    <option value="G">Priority Area G: Therapeutics: Synthesis, Formulation, Processing & Drug Delivery</option>
                    <option value="H">Priority Area H: Food for Health</option>
                    <option value="I">Priority Area I: Sustainable Food Producation & Processing</option>
                    <option value="J">Priority Area J: Marine Renewable Energy</option>
                    <option value="K">Priority Area K: Smart Grids & Smart Cities</option>
                    <option value="L">Priority Area L: Manufacturing Competiveness</option>
                    <option value="M">Priority Area M: Processing Technologies & Novel Matierials</option>
                    <option value="N">Priority Area N: Innovation in Services & Business Processes</option>
                    <option value="S">Software</option>
                    <option value="O">Other</option>
                </select>
              </div>
            </div>
            <div id="funder_form" hidden>
              <div class="form-group text-left">
                <label for="organisation">Name of Organisation</label>
                <input type="text" id="organisation" autocomplete="organization" name="organisation" class="form-control">
              </div>
            </div><br>
            <div class="col text-center">
              <button class="btn btn-success" type="submit">Create Account</button>
              <br><br>
              <p><u><a href="{% url 'accounts:login' %}">Already have an account? Login here</a></u></p>
            </div>
            </form>
      </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/reg_succes.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
<br>
<div class="container">
    <h2>Success</h2>
    <p>
        Congratulations {{ name }}, your have successfully registered.
    </p>
</div>

{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<br>
<div class="container" style="margin-left:2px">
    <h1>Reset Password</h1><br>
    <p>
        Please enter your email address to reset your password
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-danger" type="submit">Reset Password</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class="container">
    <h1>Password reset complete</h1>
    <p>
        Your password has been successfully changed,
        please login again with your new password to proceed to the website
    </p>
    <form action="{% url 'accounts:login' %}">
    <input class="btn btn-success" type="submit" value="Login" />
    </form>
</div>

{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<br>
<div class="container" style="margin-left:2px">
    <h1>Enter new password</h1>
    <p>
        Enter new password here!
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Reset Password</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class="container" style="margin-left:2px">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account
         exists with the email you entered. You should receive them shortly.
        If you don't receive an email, please make sure you've entered the
        address you registered with, and check your spam folder.
    </p>
</div>

{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
{% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
{% endautoescape %}