accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import   (
    login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
)

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^profile/password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset,
    {'template_name': 'accounts/reset_password.html',
    'post_reset_redirect': 'accounts:password_reset_done',
    'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done,
    {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html',
    'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,
    {'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

    url(r'^view-researcher/(?P<researcher_id>\d+)/$', views.view_researcher, name='view researcher'),
    url(r'^view-researcher/(?P<researcher_id>\d+)/education/new', views.add_education),
    url(r'^view-researcher/(?P<researcher_id>\d+)/education/(?P<index>\d+)', views.edit_education),
    url(r'^view-researcher/(?P<researcher_id>\d+)/employment/new', views.add_employment),
    url(r'^view-researcher/(?P<researcher_id>\d+)/employment/(?P<index>\d+)', views.edit_employment),
    url(r'^view-researcher/(?P<researcher_id>\d+)/society/new', views.add_society),
    url(r'^view-researcher/(?P<researcher_id>\d+)/society/(?P<index>\d+)', views.edit_society),
    url(r'^view-researcher/(?P<researcher_id>\d+)/award/new', views.add_award),
    url(r'^view-researcher/(?P<researcher_id>\d+)/award/(?P<index>\d+)', views.edit_award),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding/new', views.add_funding),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding/(?P<index>\d+)', views.edit_funding),
    url(r'^view-researcher/(?P<researcher_id>\d+)/team_member/new', views.add_team_member),
    url(r'^view-researcher/(?P<researcher_id>\d+)/team_member/(?P<index>\d+)', views.edit_team_member),
    url(r'^view-researcher/(?P<researcher_id>\d+)/impact/new', views.add_impact),
    url(r'^view-researcher/(?P<researcher_id>\d+)/impact/(?P<index>\d+)', views.edit_impact),
    url(r'^view-researcher/(?P<researcher_id>\d+)/innovation/new', views.add_innovation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/innovation/(?P<index>\d+)', views.edit_innovation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/publication/new', views.add_publication),
    url(r'^view-researcher/(?P<researcher_id>\d+)/publication/(?P<index>\d+)', views.edit_publication),
    url(r'^view-researcher/(?P<researcher_id>\d+)/presentation/new', views.add_presentation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/presentation/(?P<index>\d+)', views.edit_presentation),
    url(r'^view-researcher/(?P<researcher_id>\d+)/acedemic-collab/new', views.add_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/acedemic-collab/(?P<index>\d+)', views.edit_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/non_acedemic_collab/new', views.add_non_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/non_acedemic_collab/(?P<index>\d+)', views.edit_non_acedemic_collab),
    url(r'^view-researcher/(?P<researcher_id>\d+)/conference/new', views.add_conference),
    url(r'^view-researcher/(?P<researcher_id>\d+)/conference/(?P<index>\d+)', views.edit_conference),
    url(r'^view-researcher/(?P<researcher_id>\d+)/comms_overview/new', views.add_comms_overview),
    url(r'^view-researcher/(?P<researcher_id>\d+)/comms_overview/(?P<index>\d+)', views.edit_comms_overview),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding_ratio/new', views.add_funding_ratio),
    url(r'^view-researcher/(?P<researcher_id>\d+)/funding_ratio/(?P<index>\d+)', views.edit_funding_ratio),
    url(r'^view-researcher/(?P<researcher_id>\d+)/project/new', views.add_project),
    url(r'^view-researcher/(?P<researcher_id>\d+)/project/(?P<index>\d+)', views.edit_project)
]

home/urls.py
from django.conf.urls import url
from home.views import HomeView

from . import views

urlpatterns = [

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^publish_call$', views.pub, name='pub'),
    url(r'^delete_call/(?P<call_id>\d+)$', views.delete_call, name='delete_call'),
    url(r'^delete_proposal/(?P<proposal_id>\d+)$', views.delete_proposal, name='delete_proposal'),
    url(r'^call_view$', views.get_call_view, name='call_view'),
    url(r'^my_calls$', views.get_my_calls, name='my_calls'),
    url(r'^download_file$', views.download_file, name='download_file'),
    url(r'^centers$', views.view_center, name='view_center'),
    url(r'^centers/create_center$', views.create_center, name='create_center'),
    url(r'^ajax/autocomplete/$', views.autocomplete, name='ajax_autocomplete'),
    url(r'^nav_search$', views.nav_search, name='nav_search'),
    url(r'^add_to_center$', views.add_to_center, name='add_to_center'),
    url(r'^update_proposal$', views.update_proposal, name='update_proposal'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from project import views

urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
    url(r'^home/', include('home.urls', namespace='home')),

]

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from accounts.models import *


class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

class CenterForm(forms.ModelForm):
    class Meta:
        model = Center
        fields = ('name', 'info')

    def save(self, admin, commit=True):
        center = super(CenterForm, self).save(commit=False)
        center.admin = admin
        if commit:
            center.save()
            center.members.add(admin)
        return center

class CallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = '__all__'
        exclude = ('created', 'funder')

class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ('proposal_document',)

    def save(self, user, call, reviewer=None, commit=True):
        proposal = super(ProposalForm, self).save(commit=False)
        proposal.user = user
        proposal.call = call
        proposal.reviewer = reviewer
        proposal.status = "p"
        if commit:
            proposal.save()
        return proposal

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = '__all__'
        exclude = ('researcher', 'center')

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from accounts.forms import EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseForbidden
from accounts.models import *

# Create your views here.
def register(request):
    errors = []
    if request.method == 'POST':
        type = request.POST['user_type']
        user = User()
        email = request.POST['email']
        if len(User.objects.filter(email=email)) != 0:
            errors += ["Email address already in use"]
        user.email = email
        user.first_name = request.POST.get('first_name', None)
        user.last_name = request.POST.get('last_name', None)
        password = request.POST['password']
        user.set_password(password)
        user.username = email
        if type == 'funder':
            other = Funder()
            other.organisation = request.POST.get('organisation', None)
        elif type == 'reviewer':
            other = Reviewer()
            other.field = request.POST.get('field', None)
        else:
            other = Researcher()
            other.job_title = request.POST.get('job_title', None)
            other.prefix = request.POST.get('prefix', None)
            other.suffix = request.POST.get('suffix', None)
            other.phone = request.POST.get('phone', None)
            other.orcid = request.POST.get('orcid', None)
        if not errors:
            user.save()
            other.user = user
            other.save()
            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
            return redirect(reverse('home:home'))

    return render(request, 'accounts/reg_form.html', {'errors' : errors})

def view_profile(request):
    try:
        researcher = request.user.researcher
        return redirect("/account/view-researcher/%s" % request.user.id)
    except Researcher.DoesNotExist:
        storage = messages.get_messages(request)
        args = {'user': request.user, 'message': storage}
        return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method=='POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was updated!')
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method=="POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your new password has been saved!')
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))

    else:
        form = PasswordChangeForm(user=request.user)

    args = {'form': form}
    return render(request, 'accounts/change_password.html', args)


# Researcher profile views:


# view the researcher with the id researcher_id and view it with
# editing if the logged in user IS the researcher
def view_researcher(request, researcher_id):
    researcher_id = int(researcher_id)
    editing = request.user.id == researcher_id
    if editing:
        researcher = request.user.researcher
    else:
        researcher = Researcher.objects.get(user=researcher_id)
    return render(request, 'accounts/view_researcher.html', {'researcher': researcher, 'profile':researcher.profile, 'editing': editing})




def add_education(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Education',
            'is_private' : True,
            'inputs' : Education.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_education().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#education_%i' % (researcher_id, obj.index))

def edit_education(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.educations[index]
        attributes = {
            'title' : 'Edit Education',
            'is_private' : obj.is_private,
            'inputs' : Education.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.educations[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#educations_%i" % (researcher_id, index))

def add_employment(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Employment',
            'is_private' : True,
            'inputs' : Employment.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_employment().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#employment_%i' % (researcher_id, obj.index))

def edit_employment(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.employments[index]
        attributes = {
            'title' : 'Edit Employment',
            'is_private' : obj.is_private,
            'inputs' : Employment.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.employments[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#employment_%i" % (researcher_id, index))

def add_society(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Society',
            'is_private' : True,
            'inputs' : Society.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_society().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#society_%i' % (researcher_id, obj.index))

def edit_society(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.societies[index]
        attributes = {
            'title' : 'Edit Society',
            'is_private' : obj.is_private,
            'inputs' : Society.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.societies[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#society_%i" % (researcher_id, index))

def add_award(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        attributes = {
            'title' : 'New Award',
            'is_private' : True,
            'inputs' : Award.get_inputs()
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.new_award().update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect('/account/view-researcher/%i#award_%i' % (researcher_id, obj.index))

def edit_award(request, researcher_id, index):
    researcher_id = int(researcher_id)
    index = int(index)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()
    if request.method == 'GET':
        obj = request.user.researcher.profile.awards[index]
        attributes = {
            'title' : 'Edit Award',
            'is_private' : obj.is_private,
            'inputs' : Award.get_inputs(obj)
        }
        return render(request, 'accounts/form.html', attributes)
    else:
        obj = request.user.researcher.profile.awards[index].update(request.POST)
        messages.success(request, 'Your researcher  profile has been updated!')
        return redirect("/account/view-researcher/%i#award_%i" % (researcher_id, index))

def add_funding(request, researcher_id):
    researcher_id = int(researcher_id)
    if request.user.id != researcher_id:
        return HttpResponseForbidden()

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        {% block head %}
        <title>Sesame</title>
        {% endblock head %}
        {% load static %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
        <!-- script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script-->
        <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <link rel="stylesheet" href="{% static 'publishCalls/index.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script defer src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script defer src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
        <script defer src="{% static 'homeDataTable/dataTable.js' %}"></script>
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
        <script src="http://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
        <link rel="stylesheet" href = "/static/accounts/style.css">
        <!-- <script type="text/javascript" src="{% static 'bootstrap/bootstrap.min.js' %}"></script> -->
    </head>
    <body>

    <div class="container-fluid" style="padding:0px; height:100px; background-color:teal">

        <nav class="navbar navbar-expand-lg navbar-dark">

        <a class="navbar-brand logo" href="{% url 'home:home' %}">
            <img src="http://sfi.ie/site-files/cms-templates/img/sfi-logo.svg" alt="company logo" style="width: 100%;">
        </a>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% endif %}
          {% if user.is_authenticated %}
          {% if user.funder %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:my_calls' %}">My Calls<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          {% if user.researcher or user.reviewer %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:my_calls' %}">My Proposals<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          {% if user.researcher %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:view_center' %}">Centers<span class="sr-only">(current)</span></a>
          </li>
          {% endif %}
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.first_name }} {{ user.last_name }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% if user.researcher %}
                <a class="dropdown-item" href="">Researcher</a>
                {% endif %}
                {% if user.reviewer %}
                <a class="dropdown-item" href="">Reviewer</a>
                {% endif %}
                {% if user.funder %}
                <a class="dropdown-item" href="">Funder</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'accounts:view_profile' %}">View Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method='GET' action="{% url 'home:nav_search' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" id="search" name='search'>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% endif %}
      </div>
    </nav>

    {% block body %}
    <h1>Base</h1>
    {% endblock body %}
    {%block javascript %}
    <script>
        $("#search").on('keyup', function(){
            var value = $(this).val();
            $.ajax({
                url: "{% url 'home:ajax_autocomplete' %}",
                data: {
                  'search': value

                },
                dataType: 'json',
                success: function (data) {
                    list = data.list;
                    $("#search").autocomplete({
                    source: list,
                    minLength: 3,

                    });
                }
            });
        });
    </script>
    {% endblock %}
    </body>
</html>